logo: # add logo name
title: Mahaveer Satra
description: Hie there! Mahaveer Satra here, mechanical engineer artist soccer music and business fanatic # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
permalink: ':title/'
#baseurl: "/bef" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Mahaveer Satra # your name
about-author:|An outdoor fanatic, eager to learn bits and pieces about our strange world. Enjoy the articles and projects and feel free to reach out to discuss any strange idea which can improve the world. We can render it to reality.  # about author
email: mahaveersatra@gmail.com # your email
phone: (XXX)-XXX-XXXX # your phone number
website: https://mahaveersatra.github.io/ # you website

# Social link
linkedin_url:  https://www.linkedin.com/in/mahaveer-satra/ # add url link
twitter_url:   https://twitter.com/Mahaveersatra # add url link
instagram_url: https://www.instagram.com/mahaveersatra/ # add url link
medium_url:    https://mahaveersatra.medium.com/ # add url link
dribbble_url:  # add url link
facebook_url:  https://www.facebook.com/mahaveer.satra # add url link

# Disqus
discus_identifier: # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics: G-289KNPEFLS

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
